version: '2'
services:
  web:
    build:
      context: .
      dockerfile: src/main/docker/Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - .:/code
    depends_on:
      - redisserver
  redisserver:
    image: "redis:alpine"